name: "Automatically set milestone to issue"
description: "Automatically set milestone to issue"
inputs:
  github-token: # id of input
    description: "Github Token"
    required: true
  version-prefix:
    description: "version prefix"
    required: false
    default: "v"
  version-separator:
    description: "version separator"
    required: false
    default: "."
  overwrite:
    description: "whether to overwrite an existing milestone"
    type: boolean
    required: false
    default: true
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "git-pull-request"
  color: "green"
